@startuml
'https://plantuml.com/sequence-diagram

autonumber

Main -> creatFile: call function
Main-->createJava: callfunction
Main-->createCSS:callfunction
creatFile --> Main: new file created
createCSS-->Main: new file created
createJava-->Main:new file created

@enduml